sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -t mghilardelli/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true mghilardelli/docker-react npm run test
